version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-2:598723879413:task-definition/docker-pipeline:8"
        LoadBalancerInfo:
          ContainerName: "teste-build"
          ContainerPort: 80









